name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  build:
    environment: development
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g yarn
      - run: yarn
      - run: yarn run lint
      - run: yarn run build
      - run: cd dist && zip -r ../dist-${{ matrix.node-version }}.zip * && cd ..
      - uses: actions/upload-artifact@master
        with:
          name: artifact-dist
          path: dist-${{ matrix.node-version }}.zip
  deploy:
    needs: build
    environment: development
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@master
        with:
          name: artifact-dist
          path: dist-14.x.zip
      - run: ${{ secrets.SETUP_TARGET }}
      - run: scp dist-14.x.zip deployment:~/dist.zip
