name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  build:
    environment: development
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g yarn
      - run: yarn
      - run: yarn run lint
      - run: yarn run build
      - run: cd dist && zip -r ../dist.zip * && cd ..
      - uses: actions/upload-artifact@master
        with:
          name: artifact-dist-${{ matrix.node-version }}
          path: dist.zip
  deploy:
    needs: build
    environment: development
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@master
        with:
          name: artifact-dist-14.x
          path: .
      - name: Setup Target Env
        run: ${{ secrets.SETUP_TARGET }}
        env:
          SSH_USER: ${{ secrets.DEPLOY_SSH_USER }}
          SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          SSH_HOST: ${{ secrets.DEPLOY_SSH_HOST }}
      - name: Send the dist archvie to the server
        run: scp dist.zip deployment:dists/dist-$GITHUB_RUN_ID-$GITHUB_ACTION.zip
